spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: 123hazover
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Fallback: Let Hibernate create tables since Flyway baseline might have skipped V1
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true # Important for existing non-empty databases
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.example.taskmanager: INFO

app:
  jwt:
    secret: SGVsbG8gV29ybGQgSGVsbG8gV29ybGQgSGVsbG8gV29ybGQgSGVsbG8gV29ybGQgSGVsbG8gV29ybGQgSGVsbG8gV29ybGQgSGVsbG8gV29ybGQgSGVsbG8gV29ybGQ=
    expiration-ms: 86400000
